// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Job struct {
	ID       string `json:"id"`
	Filename string `json:"filename"`
	Status   string `json:"status"`
}

type Mutation struct {
}

type Query struct {
}
